# Github action for releasing the binaries
name: Publish

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: |
          npm install

      - name: Check linting
        run: |
          npm run-script lint
  
      - name: Check format
        run: |
          npm run-script check-format

      - name: Build
        run: | 
          npm run-script package

      - name: Ui test
        run: | 
          npm run-script docker-build-ui-test
          npm run-script docker-start-ui-test