# Github action for releasing the binaries
name: Publish

on:
  release:
    types: [published]
  workflow_dispatch:  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Publish on Marketplace
        run: | 
          npm install
          npm run-script vscode:publish
        env: 
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Publish on Open-vsx
        run: | 
          npm install
          npm run-script openvsx:publish
        env: 
          OVSX_PAT: ${{ secrets.OVSX_PAT }}